Update pipelines.steps.yml

diff --git a/.jfrog-pipelines/configsync/pipelines.steps.yml b/.jfrog-pipelines/configsync/pipelines.steps.yml
--- a/.jfrog-pipelines/configsync/pipelines.steps.yml
+++ b/.jfrog-pipelines/configsync/pipelines.steps.yml
@@ -106,4 +106,23 @@ pipelines:
           onExecute:
             - saas_main=$(echo {{ .Values.jpdMain }})
             - main_url="int_${saas_main}_url"
+            - main_token="int_${saas_main}_accessToken"
+            - saas_dr=$(echo {{ .Values.jpdDr }})
+            - dr_url="int_${saas_dr}_url"
+            - dr_token="int_${saas_dr}_accessToken"
+            - |
+              configure_jfrog_cli --artifactory-url "${!main_url}/artifactory" --access-token "${!main_token}" --server-name "${!saas_main}"
+              configure_jfrog_cli --artifactory-url "${!dr_url}/artifactory" --access-token "${!dr_token}" --server-name "${!saas_dr}"
+              jf c s
+              jf rt ping --server-name "${!saas_main}"
+              jf rt ping --server-name "${!saas_dr}"
+              export JFROG_CLI_LOG_LEVEL=DEBUG
+              echo "$JFROG_CLI_LOG_LEVEL - $JFROG_CLI_PLUGINS_SERVER - $JFROG_CLI_PLUGINS_REPO"
+              jf plugin install {{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}
+              if [[ $? -eq 1 ]]; then
+                echo "[ERROR] Could not install or find the $cli_plugin CLI plugin."
+                 exit 1
+              fi 
+            - echo jf {{ .Values.cliPlugin.name }} update {{ .Values.jpdMain }} --yaml-file="config-sync/yaml-input/input.yaml"  --dry-run=false
+            - jf {{ .Values.cliPlugin.name }} -v
 
